In [1]:
import numpy as np

Make some arrays

In [15]:
a = np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
a = a.reshape((2,5))
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [19]:
b = np.arange(10,20).reshape((2,5))
print(b)

[[10 11 12 13 14]
 [15 16 17 18 19]]


Put some arrays together

In [23]:
c = np.hstack([a,b])
print(c)

[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


In [24]:
d = np.vstack([a,b])
print(d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
b = numpy.array([[2, 100, 238],
                 [2, 100, 237], 
                 [4, 100, 237],
                 [4, 100, 236]])
numpy.mean(a, axis=0)